### ISSUE TITLE
cli: with-keep-cwd not a valid option

### ISSUE THREAD

**Issue by jbenito3** [inveniosoftware-attic/kwalitee#107]
`with-keep-cwd` is not a valid option for `git rev-list`.

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/kwalitee/cli/check.py", line 110, in message
    commits = _pygit2_commits(commit, repository)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/kwalitee/cli/check.py", line 59, in _pygit2_commits
    from pygit2 import Repository, GIT_SORT_TOPOLOGICAL
ImportError: No module named 'pygit2'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/bin/kwalitee", line 9, in <module>
    load_entry_point('kwalitee==0.2.0rc8', 'console_scripts', 'kwalitee')()
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/kwalitee/cli/__init__.py", line 45, in main
    manager.run()
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/kwalitee/cli/check.py", line 114, in message
    commits = _git_commits(commit, repository)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/kwalitee/cli/check.py", line 52, in _git_commits
    commits = list(g.iter_commits(commit, **kwargs))
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/git/objects/commit.py", line 279, in _iter_from_process_or_stream
    finalize_process(proc_or_stream)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/git/util.py", line 336, in finalize_process
    proc.wait(**kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/git/cmd.py", line 290, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
  cmdline: git rev-list --with-keep-cwd 9aedba249cd1a028a826572e14517bfdc5ab588c^..3c50c60d2d12512fcb36ba7309070f8c27b995b2 --
  stderr: 'usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
```

**Comment by kaplun** [comment]
@michamos this is the same error we have just seen.
